data:
  kaggle_dataset: "sainikhileshreddy/food-recognition-2022"
  dataset_zip_name: "food-recognition-2022.zip"

paths:
  artifacts_dir: "artifacts"
  extracted_data_dir: "artifacts/FoodRecognition/extracted_data"
  processing_train_data: "artifacts/FoodRecognition/extracted_data/raw_data/public_training_set_release_2.0"
  processing_val_data: "artifacts/FoodRecognition/extracted_data/raw_data/public_validation_set_2.0"
  processing_test_data: "artifacts/FoodRecognition/extracted_data/raw_data/public_test_release_2.0"
  training_data: "artifacts/FoodRecognition/Output/organized_training_data"
  val_data: "artifacts/FoodRecognition/Output/organized_validation_data"
  output_dir: "artifacts/FoodRecognition/Output"
  best_model: "artifacts/FoodRecognition/Output/final_model.h5"
  training_log: "artifacts/FoodRecognition/Output/TrainingLogs.csv"
  evaluation_metrics: "artifacts/FoodRecognition/Output/EvaluationMetrics.json"
  classification_report: "artifacts/FoodRecognition/Output/ClassificationReport.txt"
  class_indices: "artifacts/FoodRecognition/Output/class_indices.json"


mlflow:
  experiment_name: "FoodRecognition_Training"

wandb:
  project_name: "FoodRecognition_Evaluation"
  evaluation_run_name: "stage04_model_evaluation"

train:
  epochs: 1
  batch_size: 32
  patience: 5

evaluate:
  batch_size: 32
  image_size: [224, 224]

  